/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedRoomEventName = "CreatedRoom";

/**
 * Triggered when the user creates a room.
 */
export interface CreatedRoom {
  eventName: CreatedRoomEventName;
  /**
   * Whether the room is a DM.
   */
  isDM: boolean;
}
