/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ErrorEventName = "Error";
export type ErrorDomain = "E2EE" | "VOIP";
export type ErrorName =
  | "UnknownError"
  | "OlmIndexError"
  | "OlmKeysNotSentError"
  | "OlmUnspecifiedError"
  | "VoipUserHangup"
  | "VoipIceFailed"
  | "VoipInviteTimeout"
  | "VoipIceTimeout"
  | "VoipUserMediaFailed";

/**
 * Triggered when an error occurred
 */
export interface Error {
  eventName: ErrorEventName;
  domain: ErrorDomain;
  name: ErrorName;
  /**
   * Context - client defined, can be used for debugging
   */
  context?: string;
}
