/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The user properties to apply when identifying
 */
export interface Identity {
  eventName?: "Identity";
  /**
   * The selected messaging use case during the onboarding flow.
   */
  ftueUseCaseSelection?: "FriendsAndFamily" | "Teams" | "Communities" | "Skipped";
}
