/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The user properties to apply when identifying. These properties should all be device independent.
 */
export interface Identify {
  eventName?: "$identify";
  /**
   * The selected messaging use case during the onboarding flow.
   */
  ftueUseCaseSelection?: ("PersonalMessaging" | "WorkMessaging" | "CommunityMessaging" | "Skip") & string;
}
