/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when the user joins a room.
 */
export interface JoinedRoom {
  eventName: "JoinedRoom";
  /**
   * The reason for the room change if known.
   */
  trigger?: ("RoomDirectory" | "SpaceHierarchy" | "Timeline" | "Notification") & string;
  /**
   * The size of the room.
   */
  roomSize: "One" | "Two" | "ThreeToTen" | "ElevenToOneHundred" | "OneHundredAndOneToAThousand" | "MoreThanAThousand";
  /**
   * Whether the room is a DM.
   */
  isDM: boolean;
  /**
   * Whether the room is a Space.
   */
  isSpace: boolean;
}
