/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when the user changed screen on Element Android/iOS
 */
export interface MobileScreen {
  eventName: "$screen";
  screenName: (
    | "Home"
    | "Welcome"
    | "Login"
    | "ForgotPassword"
    | "Register"
    | "Room"
    | "RoomDetails"
    | "RoomMembers"
    | "User"
    | "RoomSearch"
    | "RoomUploads"
    | "RoomSettings"
    | "RoomNotifications"
    | "RoomDirectory"
    | "RoomFilter"
    | "StartChat"
    | "CreateRoom"
    | "DeactivateAccount"
    | "Group"
    | "MyGroups"
    | "SpaceExploreRooms"
    | "Sidebar"
    | "Favourites"
    | "People"
    | "Rooms"
    | "Dialpad"
    | "SearchRooms"
    | "SearchMessages"
    | "SearchPeople"
    | "SearchFiles"
    | "SwitchDirectory"
    | "InviteFriends"
    | "Breadcrumbs"
    | "Settings"
    | "SettingsSecurity"
    | "SettingsDefaultNotifications"
    | "SettingsMentionsAndKeywords"
    | "SpaceMenu"
    | "SpaceMembers"
  ) &
    string;
  /**
   * How long the screen was displayed for in milliseconds.
   */
  durationMs?: number;
}
