/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered after timing a long running operation in the app.
 */
export interface PerformanceTimer {
  eventName: "PerformanceTimer";
  /**
   * The timer that is being reported.
   */
  name:
    | "StartupInitialSync"
    | "StartupIncrementalSync"
    | "StartupStorePreload"
    | "StartupStoreReady"
    | "StartupLaunchScreen"
    | "InitialSyncRequest"
    | "InitialSyncParsing";
  /**
   * The time reported by the timer in milliseconds.
   */
  timeMs: number;
  /**
   * Client defined, can be used for debugging.
   */
  context?: string;
}
