/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when the user sends a message
 */
export interface SendMessage {
  eventName?: "SendMessage";
  roomId: string;
  threadId?: string;
  isEdit?: boolean;
  isReply?: boolean;
  msgType?: string;
  format?: string;
  localEchoDurationMs?: number;
}
