/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when a new user accepts the analytics prompt that is shown during the registration flow.
 */
export interface Signup {
  eventName: "Signup";
  /**
   * The type of authentication that was used to sign up.
   */
  authenticationType?: (
    | "Password"
    | "SignInWithApple"
    | "SignInWithFacebook"
    | "SignInWithGitHub"
    | "SignInWithGitLab"
    | "SignInWithGoogle"
    | "SSO"
  ) &
    string;
}
