/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used to track the performance of startup operations.
 */
export interface StartupPerformance {
  eventName: "StartupPerformance";
  /**
   * The operation that was profiled.
   */
  operation: "InitialSync" | "IncrementalSync" | "StorePreload" | "MountData" | "LaunchScreen";
  /**
   * The length of the operation in milliseconds.
   */
  durationMs: number;
  /**
   * Client defined, can be used for debugging.
   */
  context?: string;
}
