/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when the user becomes unauthenticated without actually clicking sign out(E.g. Due to expiry of an access token without a way to refresh).
 */
export interface UnauthenticatedError {
  eventName?: "UnauthenticatedError";
  /**
   * Whether the auth mechanism is refresh-token-based.
   */
  refreshTokenAuth: boolean;
  /**
   * Whether a soft logout or hard logout was triggered.
   */
  softLogout: boolean;
  /**
   * The error code as defined in matrix spec.
   */
  errorCode?: string;
  /**
   * The reason for the error.
   */
  errorReason?: string;
}
