/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Triggered when the user changed screen on Element Web/Desktop
 */
export interface WebScreen {
  eventName: "$pageview";
  $current_url: (
    | "Home"
    | "Welcome"
    | "Login"
    | "ForgotPassword"
    | "Register"
    | "Room"
    | "RoomDetails"
    | "RoomMembers"
    | "User"
    | "RoomSearch"
    | "RoomUploads"
    | "RoomSettings"
    | "RoomNotifications"
    | "RoomDirectory"
    | "RoomFilter"
    | "StartChat"
    | "CreateRoom"
    | "DeactivateAccount"
    | "Group"
    | "MyGroups"
    | "SpaceExploreRooms"
    | "Loading"
    | "CompleteSecurity"
    | "E2ESetup"
    | "SoftLogout"
    | "UserSettingsGeneral"
    | "UserSettingsAppearance"
    | "UserSettingsNotifications"
    | "UserSettingsPreferences"
    | "UserSettingsKeyboard"
    | "UserSettingsSidebar"
    | "UserSettingsVoiceVideo"
    | "UserSettingsSecurityPrivacy"
    | "UserSettingsLabs"
    | "UserSettingsIgnoredUsers"
    | "UserSettingsHelpAbout"
    | "UserSettingMjolnir"
    | "UserSettingFlair"
  ) &
    string;
  /**
   * How long the screen took to load, if applicable.
   */
  durationMs?: number;
}
