/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PageView {
  eventName?: "$pageview";
  /**
   * The amount of time it took to switch between this page and the last, in ms
   */
  durationMs?: number;
  /**
   * The name of the screen
   */
  screen?: string;
}
