name: Validate Kotlin

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-20.04

    concurrency:
      # When running on main, use the sha to allow all runs of this workflow to run concurrently.
      # Otherwise only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ github.ref == 'refs/heads/main' && format('kotlin-main-{0}', github.sha) || format('kotlin-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build for Kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build detekt
          build-root-directory: kotlin
